### ISSUE TITLE
How does this project load the obj

### ISSUE THREAD

**Issue by gaojunxiaowwww8888** [AnalyticalGraphicsInc/cesium-threejs-experiment#1]
How does this project load the obj model and how to introduce the OBJLoader.js plug-in?

**Comment by likangning93** [comment]
Most of the code is in `public/CesiumThree.js` A good place to start might be around [here](https://github.com/AnalyticalGraphicsInc/cesium-threejs-experiment/blob/master/public/CesiumThree.js#L140.), where ThreeJS geometries are loaded.

You could try adding plugins to the `Public/ThirdParty` folder after installing using the scripts indicated on the README page.

Please see this blog post for more information on this demo: https://cesium.com/blog/2017/10/23/integrating-cesium-with-threejs/

Finally, if possible please use the [Cesium forum](https://cesiumjs.org/forum/) for general questions on  using Cesium or our other projects. We prefer to use this space for tracking bugs. Thanks!
