### ISSUE TITLE
Globe is not visible

### ISSUE THREAD

**Issue by trusktr** [AnalyticalGraphicsInc/cesium-threejs-experiment#5]
I don't see a globe in the live demo:

<img width="1346" alt="screen shot 2018-05-30 at 12 26 47 am" src="https://user-images.githubusercontent.com/297678/40705640-48f12832-63a0-11e8-9432-385a504f7d15.png">

**Comment by lilleyse** [comment]
The Cesium version used in this demo is pretty out of date and the imagery token must have expired. @likangning93 can you update to the newest version of Cesium? (Might need to disable log depth).
